#!/bin/bash

# Args: namespace, kubectl command, resource type
# Defaults: namespace=default, command=top, resource=pod

NAMESPACE=${1:-default}
COMMAND=${2:-top}
RESOURCE_TYPE=${3:-pod}

kubectl $COMMAND $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read -r line
do
  NAME=$(echo "$line" | awk '{print $1}')
  CPU=$(echo "$line" | awk '{print $2}')
  MEMORY=$(echo "$line" | awk '{print $3}')

  echo "$RESOURCE_TYPE,$NAMESPACE,$NAME,$CPU,$MEMORY"
done
